### ISSUE TITLE
Data from DPS to unified data

### ISSUE THREAD

**Issue by Devamitta** [vijjo/DiffText#1]
You corrected the "bag":
[quote]
The bug is that:
when find a match in similarity , sbs_chant_pali, sbs_chant_eng, and sbs_chapter will be transferred from dps examples into dpd ones, even though dpd doesn’t have such columns.
[/quote]

But it is not a bug. It is correct behavior. In our unified data we need to have sbs_chant_pali, sbs_chant_eng, and sbs_chapter transferred from dps if example is match

**Comment by vijjo** [comment]
No, bhante. When there’s a match, we dont keep the dps example but use the dpd one. So it’s problematic. I recommend you reload the data with the fixed output.

**Comment by Devamitta** [comment]
That's the whole point of this code:
when there is a match with DPD we keep DPD 3 fields `source_1`, `sutta_1`  and `example_1` and keep DPS 'sbs_chant_pali_1', 'sbs_chant_eng_1', 'sbs_chapter_1'
in other words:
if DPD_example_1 much example_1 :
u1_source = DPD_source_1
u1_sutta =  DPD_sutta_1
u1_example = DPD_example_1
u1_chant_pali = sbs_chant_pali_1 
u1_chant_eng = sbs_chant_eng_1
u1_sbs_chapter = sbs_chapter_1

and same way for u2
because in DPD columns sbs_chant_pali sbs_chant_eng sbs_chapter does not exist

so previously code gave a correct result. I checked it.

**Comment by vijjo** [comment]
Bhante, the match will only about 80%. DPD and DPS might not even be the same sutta!

**Comment by Devamitta** [comment]
Yes but almost the same passage. Priority is not to keep similar examples. And with individual problems we will be dealing case by case later.

**Comment by vijjo** [comment]
I mean you should update the database with the new output files

**Comment by vijjo** [comment]
> Yes but almost the same passage. Priority is not to keep similar examples. And with individual problems we will be dealing case by case later.

The bug causes  `sbs_chant_pali`, `sbs_chant_eng`, and `sbs_chapter` to attach to the wrong example when the DPD and DPS are similar but different in source. It'd better to update the database again.

**Comment by Devamitta** [comment]
I have seen the file which you put in my shared folder. It has 1000 examples in u1 which do not have any information in sbs_chant_pali, sbs_chant_eng, and sbs_chapter. But they should have it, because even if sutta number and name is different it is similar sentences. 80% is good enough for me. Otherwise we miss this sentences in SBS Anki deck, or we would have very identical sentences.
I still think that code should work like this:


> when there is a match with DPD we keep DPD 3 fields `source_1`, `sutta_1` and `example_1` and keep DPS 'sbs_chant_pali_1', 'sbs_chant_eng_1', 'sbs_chapter_1' 
> 
> in other words: if DPD_example_1 much example_1 : u1_source = DPD_source_1 u1_sutta = DPD_sutta_1 u1_example = DPD_example_1 u1_chant_pali = sbs_chant_pali_1 u1_chant_eng = sbs_chant_eng_1 u1_sbs_chapter = sbs_chapter_1
> 
> and same way for u2 because in DPD columns sbs_chant_pali sbs_chant_eng sbs_chapter does not exist

**Comment by Devamitta** [comment]
Example:
gharāvāsa even source is different, but sentence is the same. So it should have SBS chanting book info in the u1

but in ountut-fixed it has u1_chant_pali	u1_chant_eng	u1_sbs_chapter empy and nothing in u3, so the info from SBS chanting book just missing

**Comment by vijjo** [comment]
Ok bhante. If you find it’s not a bug but a feature, it all went well 👌 I was freaked out when realizing the bug.
I’ll comment that bug in the code then, in case it might be of use later.

**Comment by Devamitta** [comment]
The code was very useful to unify data. sādhu!

Now, I would like to describe how this code will be used regularly:

Compare DPS examples with DPD examples and move examples keeping existing order and give priority to DPD examples:

DPS: 1A 2B 3C 4D
DPD: 1A 2E
Unified: 1A 2E 2B 3C 4D

DPS 1A 2B 3C 4D
DPD: 3C 2E
Unified: 3C 2E 3A 4B 4D

and so on.

the difference is - we do not need that part about new order (SBS first, class second, etc.) because we have already done it, and now I manually may correct it in some cases.

And we can increase match to 90% because most of the unification process already done and only if DPD examples will change in future we will need to run this code time after time.
